import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';
import { CustomerAccountService, CustomerAddress } from '../../services/customer-account.service';
import { FocusTrapDirective } from '../../directives/focus-trap.directive';

@Component({ selector: 'app-customer-account', standalone: true, imports: [CommonModule, FormsModule, FocusTrapDirective], template: `
@if (auth.isCustomerAccountOpen() && auth.customerUser(); as user) {
<div class="fixed inset-0 z-50 overflow-y-auto bg-stone-900/60 p-4 sm:flex sm:items-center sm:justify-center" role="dialog" aria-modal="true" aria-labelledby="account-title"><div appFocusTrap class="mx-auto w-full max-w-3xl rounded-3xl bg-white p-5 shadow-2xl sm:p-7"><div class="flex items-start justify-between"><div><h2 id="account-title" class="text-xl font-black text-stone-900">Mi cuenta</h2><p class="text-xs text-stone-500">{{ user.email }}</p></div><button (click)="auth.isCustomerAccountOpen.set(false)" class="rounded-xl p-2 text-stone-500 hover:bg-stone-100" aria-label="Cerrar">×</button></div>
@if (account.isLoading()) { <p class="mt-6 text-sm text-stone-500">Cargando tu información…</p> } @else { <div class="mt-6 grid gap-6 md:grid-cols-2"><section><h3 class="font-bold text-stone-900">Perfil</h3><div class="mt-3 space-y-2"><input [(ngModel)]="profile.full_name" class="w-full rounded-xl border p-3 text-sm" placeholder="Nombre completo"><input [(ngModel)]="profile.phone" class="w-full rounded-xl border p-3 text-sm" placeholder="Teléfono"><button (click)="saveProfile(user.id)" class="rounded-xl bg-stone-900 px-4 py-2 text-xs font-bold text-white">Guardar perfil</button></div><h3 class="mt-6 font-bold text-stone-900">Direcciones</h3><div class="mt-3 space-y-2">@for (address of account.addresses(); track address.id) { <div class="rounded-xl border p-3 text-xs"><b>{{ address.recipient_name }}</b><br>{{ address.line1 }}, {{ address.city }}, {{ address.state }} {{ address.postal_code }}<button (click)="removeAddress(address.id!)" class="mt-2 text-rose-600">Eliminar</button></div> }<div class="rounded-xl border border-dashed p-3 space-y-2"><input [(ngModel)]="address.recipient_name" class="w-full rounded-lg border p-2 text-xs" placeholder="Destinatario"><input [(ngModel)]="address.phone" class="w-full rounded-lg border p-2 text-xs" placeholder="Teléfono"><input [(ngModel)]="address.line1" class="w-full rounded-lg border p-2 text-xs" placeholder="Calle y número"><input [(ngModel)]="address.city" class="w-full rounded-lg border p-2 text-xs" placeholder="Ciudad"><input [(ngModel)]="address.state" class="w-full rounded-lg border p-2 text-xs" placeholder="Estado"><input [(ngModel)]="address.postal_code" class="w-full rounded-lg border p-2 text-xs" placeholder="Código postal"><label class="flex gap-2 text-xs"><input type="checkbox" [(ngModel)]="address.is_default"> Predeterminada</label><button (click)="saveAddress()" class="rounded-xl bg-stone-900 px-3 py-2 text-xs font-bold text-white">Agregar dirección</button></div></div></section><section><h3 class="font-bold text-stone-900">Mis pedidos</h3>@if (account.orders().length === 0) { <p class="mt-3 text-xs text-stone-500">Aún no tienes pedidos.</p> } @else { <div class="mt-3 space-y-2">@for (order of account.orders(); track order.id) { <article class="rounded-xl border p-3 text-xs"><div class="flex justify-between"><b>{{ order.order_number }}</b><b>\${{ order.total | number:'1.2-2' }}</b></div><p class="mt-1 text-stone-500">{{ order.status }} · {{ order.created_at | date:'mediumDate' }}</p>@for (item of order.order_items || []; track item.product_name) { <p class="text-stone-600">{{ item.quantity }}× {{ item.product_name }}</p> }</article> }</div> }</section></div> }</div></div> }
` })
export class CustomerAccountComponent {
  public auth = inject(AuthService); public account = inject(CustomerAccountService);
  public profile = { ...this.account.profile() };
  public address: CustomerAddress = { recipient_name: '', phone: '', line1: '', city: '', state: '', postal_code: '', country: 'MX', is_default: false };
  constructor() { void this.open(); }
  public async open(): Promise<void> { const user = this.auth.customerUser(); if (user) { await this.account.load(user.id); this.profile = { ...this.account.profile() }; } }
  public saveProfile(id: string): void { void this.account.saveProfile(id, this.profile); }
  public saveAddress(): void { if (this.address.recipient_name && this.address.phone && this.address.line1 && this.address.city && this.address.state && this.address.postal_code) { void this.account.saveAddress(this.address); this.address = { recipient_name: '', phone: '', line1: '', city: '', state: '', postal_code: '', country: 'MX', is_default: false }; } }
  public removeAddress(id: string): void { void this.account.removeAddress(id); }
}
